// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RedYellowGreen.Api.Infrastructure.Database;

#nullable disable

namespace RedYellowGreen.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205134709_AddEquipmentAndOrders")]
    partial class AddEquipmentAndOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RedYellowGreen.Api.Features.Equipment.Models.EquipmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RedYellowGreen.Api.Features.Equipment.Models.EquipmentStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("State");

                    b.ToTable("EquipmentStates", (string)null);
                });

            modelBuilder.Entity("RedYellowGreen.Api.Features.Orders.Models.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RedYellowGreen.Api.Features.Equipment.Models.EquipmentEntity", b =>
                {
                    b.OwnsOne("RedYellowGreen.Api.Features.Equipment.Models.EquipmentEntity+EquipmentCurrentState", "CurrentState", b1 =>
                        {
                            b1.Property<Guid>("EquipmentEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<Guid>("StateId")
                                .HasColumnType("uuid");

                            b1.HasKey("EquipmentEntityId");

                            b1.HasIndex("State");

                            b1.ToTable("Equipment");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentEntityId");
                        });

                    b.Navigation("CurrentState")
                        .IsRequired();
                });

            modelBuilder.Entity("RedYellowGreen.Api.Features.Equipment.Models.EquipmentStateEntity", b =>
                {
                    b.HasOne("RedYellowGreen.Api.Features.Equipment.Models.EquipmentEntity", "Equipment")
                        .WithMany("States")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("RedYellowGreen.Api.Features.Orders.Models.OrderEntity", b =>
                {
                    b.HasOne("RedYellowGreen.Api.Features.Equipment.Models.EquipmentEntity", "Equipment")
                        .WithMany("Orders")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("RedYellowGreen.Api.Features.Equipment.Models.EquipmentEntity", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
